# stuck on 2 as we need `extends`. Alternatives seem bad. https://github.com/moby/moby/issues/31101
version: '2'

services:
  dev:
    build:
      dockerfile: support/dev/Dockerfile
      context: .
    command: bash
    working_dir: /work
    volumes:
      - .:/work
      - ruby2.5-gem-cache:/usr/local/bundle

  dev-run:
    extends:
      service: dev
    command: support/dev/run
    ports:
      - 4000:4000

volumes:
  ruby2.5-gem-cache:
    external: true
